package com.contravenciones.tr.persistence;
// Generated 5/02/2018 01:39:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CivCobrocoactivo generated by hbm2java
 */
public class CivCobrocoactivo  implements java.io.Serializable {


     private BigDecimal cobcoId;
     private CivResoluciones civResoluciones;

    public CivCobrocoactivo() {
    }

    public CivCobrocoactivo(BigDecimal cobcoId, CivResoluciones civResoluciones) {
       this.cobcoId = cobcoId;
       this.civResoluciones = civResoluciones;
    }
   
    public BigDecimal getCobcoId() {
        return this.cobcoId;
    }
    
    public void setCobcoId(BigDecimal cobcoId) {
        this.cobcoId = cobcoId;
    }
    public CivResoluciones getCivResoluciones() {
        return this.civResoluciones;
    }
    
    public void setCivResoluciones(CivResoluciones civResoluciones) {
        this.civResoluciones = civResoluciones;
    }




}


