package com.contravenciones.tr.persistence;
// Generated 29/01/2018 01:31:54 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;

/**
 * CivCargueplano generated by hbm2java
 */
public class CivCargueplano  implements java.io.Serializable {


     private BigDecimal carplaId;
     private String carplaNombre;
     private Date carplaFechaCargue;
     private BigDecimal usuId;
     private BigDecimal carplaEstado;
     private Blob carplaArchivo;

    public CivCargueplano() {
    }

	
    public CivCargueplano(BigDecimal carplaId) {
        this.carplaId = carplaId;
    }
    public CivCargueplano(BigDecimal carplaId, String carplaNombre, Date carplaFechaCargue, BigDecimal usuId, BigDecimal carplaEstado, Blob carplaArchivo) {
       this.carplaId = carplaId;
       this.carplaNombre = carplaNombre;
       this.carplaFechaCargue = carplaFechaCargue;
       this.usuId = usuId;
       this.carplaEstado = carplaEstado;
       this.carplaArchivo = carplaArchivo;
    }
   
    public BigDecimal getCarplaId() {
        return this.carplaId;
    }
    
    public void setCarplaId(BigDecimal carplaId) {
        this.carplaId = carplaId;
    }
    public String getCarplaNombre() {
        return this.carplaNombre;
    }
    
    public void setCarplaNombre(String carplaNombre) {
        this.carplaNombre = carplaNombre;
    }
    public Date getCarplaFechaCargue() {
        return this.carplaFechaCargue;
    }
    
    public void setCarplaFechaCargue(Date carplaFechaCargue) {
        this.carplaFechaCargue = carplaFechaCargue;
    }
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }
    public BigDecimal getCarplaEstado() {
        return this.carplaEstado;
    }
    
    public void setCarplaEstado(BigDecimal carplaEstado) {
        this.carplaEstado = carplaEstado;
    }
    public Blob getCarplaArchivo() {
        return this.carplaArchivo;
    }
    
    public void setCarplaArchivo(Blob carplaArchivo) {
        this.carplaArchivo = carplaArchivo;
    }




}


