package com.contravenciones.tr.persistence;
// Generated 26/01/2018 03:08:11 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivCarguecomparendo generated by hbm2java
 */
public class CivCarguecomparendo  implements java.io.Serializable {


     private long carcompId;
     private String comconsecutivo;
     private String comnumero;
     private String comfecha;
     private String comhora;
     private String comdir;
     private String comdivipomuni;
     private String comlocalidadcomuna;
     private String complaca;
     private String comdivipomatri;
     private String comtipovehi;
     private String comtiposer;
     private String comcodigoradio;
     private String comcodigomodalidad;
     private String comcodigopasajeros;
     private String cominfractor;
     private String comtipodoc;
     private String comnombe;
     private String comapellido;
     private String comedadinfractor;
     private String comdirinfractor;
     private String comemail;
     private String comteleinfractor;
     private String comidciudad;
     private String comlicencia;
     private String comcategoria;
     private String comsecreexpide;
     private String comfechavence;
     private String comtipoinfrac;
     private String complictransito;
     private String comdivipolicen;
     private String comidentificacion;
     private String comidtipodocprop;
     private String comnombreprop;
     private String comnombreempresa;
     private String comnitempresa;
     private String comtarjetaoperacion;
     private String compplacaagente;
     private String comobserva;
     private String comfuga;
     private String comacci;
     private String cominmov;
     private String compatioinmoviliza;
     private String comdirpatioinmovi;
     private String comgruanumero;
     private String complacagrua;
     private String comconsecutiinmovi;
     private String comidentificaciontest;
     private String comnombretesti;
     private String comdirecrestesti;
     private String comteletestigo;
     private String comvalor;
     private String comvalad;
     private String comorganismo;
     private String comestadocom;
     private String compolca;
     private String cominfraccion;
     private String comvalinfra;
     private String gradoalcohol;
     private String fotomulta;
     private String fechaDeNotificacion;
     private BigDecimal estado;
     private Date fechaProceso;
     private String descripcionError;
     private BigDecimal carplaId;

    public CivCarguecomparendo() {
    }

	
    public CivCarguecomparendo(long carcompId) {
        this.carcompId = carcompId;
    }
    public CivCarguecomparendo(long carcompId, String comconsecutivo, String comnumero, String comfecha, String comhora, String comdir, String comdivipomuni, String comlocalidadcomuna, String complaca, String comdivipomatri, String comtipovehi, String comtiposer, String comcodigoradio, String comcodigomodalidad, String comcodigopasajeros, String cominfractor, String comtipodoc, String comnombe, String comapellido, String comedadinfractor, String comdirinfractor, String comemail, String comteleinfractor, String comidciudad, String comlicencia, String comcategoria, String comsecreexpide, String comfechavence, String comtipoinfrac, String complictransito, String comdivipolicen, String comidentificacion, String comidtipodocprop, String comnombreprop, String comnombreempresa, String comnitempresa, String comtarjetaoperacion, String compplacaagente, String comobserva, String comfuga, String comacci, String cominmov, String compatioinmoviliza, String comdirpatioinmovi, String comgruanumero, String complacagrua, String comconsecutiinmovi, String comidentificaciontest, String comnombretesti, String comdirecrestesti, String comteletestigo, String comvalor, String comvalad, String comorganismo, String comestadocom, String compolca, String cominfraccion, String comvalinfra, String gradoalcohol, String fotomulta, String fechaDeNotificacion, BigDecimal estado, Date fechaProceso, String descripcionError, BigDecimal carplaId) {
       this.carcompId = carcompId;
       this.comconsecutivo = comconsecutivo;
       this.comnumero = comnumero;
       this.comfecha = comfecha;
       this.comhora = comhora;
       this.comdir = comdir;
       this.comdivipomuni = comdivipomuni;
       this.comlocalidadcomuna = comlocalidadcomuna;
       this.complaca = complaca;
       this.comdivipomatri = comdivipomatri;
       this.comtipovehi = comtipovehi;
       this.comtiposer = comtiposer;
       this.comcodigoradio = comcodigoradio;
       this.comcodigomodalidad = comcodigomodalidad;
       this.comcodigopasajeros = comcodigopasajeros;
       this.cominfractor = cominfractor;
       this.comtipodoc = comtipodoc;
       this.comnombe = comnombe;
       this.comapellido = comapellido;
       this.comedadinfractor = comedadinfractor;
       this.comdirinfractor = comdirinfractor;
       this.comemail = comemail;
       this.comteleinfractor = comteleinfractor;
       this.comidciudad = comidciudad;
       this.comlicencia = comlicencia;
       this.comcategoria = comcategoria;
       this.comsecreexpide = comsecreexpide;
       this.comfechavence = comfechavence;
       this.comtipoinfrac = comtipoinfrac;
       this.complictransito = complictransito;
       this.comdivipolicen = comdivipolicen;
       this.comidentificacion = comidentificacion;
       this.comidtipodocprop = comidtipodocprop;
       this.comnombreprop = comnombreprop;
       this.comnombreempresa = comnombreempresa;
       this.comnitempresa = comnitempresa;
       this.comtarjetaoperacion = comtarjetaoperacion;
       this.compplacaagente = compplacaagente;
       this.comobserva = comobserva;
       this.comfuga = comfuga;
       this.comacci = comacci;
       this.cominmov = cominmov;
       this.compatioinmoviliza = compatioinmoviliza;
       this.comdirpatioinmovi = comdirpatioinmovi;
       this.comgruanumero = comgruanumero;
       this.complacagrua = complacagrua;
       this.comconsecutiinmovi = comconsecutiinmovi;
       this.comidentificaciontest = comidentificaciontest;
       this.comnombretesti = comnombretesti;
       this.comdirecrestesti = comdirecrestesti;
       this.comteletestigo = comteletestigo;
       this.comvalor = comvalor;
       this.comvalad = comvalad;
       this.comorganismo = comorganismo;
       this.comestadocom = comestadocom;
       this.compolca = compolca;
       this.cominfraccion = cominfraccion;
       this.comvalinfra = comvalinfra;
       this.gradoalcohol = gradoalcohol;
       this.fotomulta = fotomulta;
       this.fechaDeNotificacion = fechaDeNotificacion;
       this.estado = estado;
       this.fechaProceso = fechaProceso;
       this.descripcionError = descripcionError;
       this.carplaId = carplaId;
    }
   
    public long getCarcompId() {
        return this.carcompId;
    }
    
    public void setCarcompId(long carcompId) {
        this.carcompId = carcompId;
    }
    public String getComconsecutivo() {
        return this.comconsecutivo;
    }
    
    public void setComconsecutivo(String comconsecutivo) {
        this.comconsecutivo = comconsecutivo;
    }
    public String getComnumero() {
        return this.comnumero;
    }
    
    public void setComnumero(String comnumero) {
        this.comnumero = comnumero;
    }
    public String getComfecha() {
        return this.comfecha;
    }
    
    public void setComfecha(String comfecha) {
        this.comfecha = comfecha;
    }
    public String getComhora() {
        return this.comhora;
    }
    
    public void setComhora(String comhora) {
        this.comhora = comhora;
    }
    public String getComdir() {
        return this.comdir;
    }
    
    public void setComdir(String comdir) {
        this.comdir = comdir;
    }
    public String getComdivipomuni() {
        return this.comdivipomuni;
    }
    
    public void setComdivipomuni(String comdivipomuni) {
        this.comdivipomuni = comdivipomuni;
    }
    public String getComlocalidadcomuna() {
        return this.comlocalidadcomuna;
    }
    
    public void setComlocalidadcomuna(String comlocalidadcomuna) {
        this.comlocalidadcomuna = comlocalidadcomuna;
    }
    public String getComplaca() {
        return this.complaca;
    }
    
    public void setComplaca(String complaca) {
        this.complaca = complaca;
    }
    public String getComdivipomatri() {
        return this.comdivipomatri;
    }
    
    public void setComdivipomatri(String comdivipomatri) {
        this.comdivipomatri = comdivipomatri;
    }
    public String getComtipovehi() {
        return this.comtipovehi;
    }
    
    public void setComtipovehi(String comtipovehi) {
        this.comtipovehi = comtipovehi;
    }
    public String getComtiposer() {
        return this.comtiposer;
    }
    
    public void setComtiposer(String comtiposer) {
        this.comtiposer = comtiposer;
    }
    public String getComcodigoradio() {
        return this.comcodigoradio;
    }
    
    public void setComcodigoradio(String comcodigoradio) {
        this.comcodigoradio = comcodigoradio;
    }
    public String getComcodigomodalidad() {
        return this.comcodigomodalidad;
    }
    
    public void setComcodigomodalidad(String comcodigomodalidad) {
        this.comcodigomodalidad = comcodigomodalidad;
    }
    public String getComcodigopasajeros() {
        return this.comcodigopasajeros;
    }
    
    public void setComcodigopasajeros(String comcodigopasajeros) {
        this.comcodigopasajeros = comcodigopasajeros;
    }
    public String getCominfractor() {
        return this.cominfractor;
    }
    
    public void setCominfractor(String cominfractor) {
        this.cominfractor = cominfractor;
    }
    public String getComtipodoc() {
        return this.comtipodoc;
    }
    
    public void setComtipodoc(String comtipodoc) {
        this.comtipodoc = comtipodoc;
    }
    public String getComnombe() {
        return this.comnombe;
    }
    
    public void setComnombe(String comnombe) {
        this.comnombe = comnombe;
    }
    public String getComapellido() {
        return this.comapellido;
    }
    
    public void setComapellido(String comapellido) {
        this.comapellido = comapellido;
    }
    public String getComedadinfractor() {
        return this.comedadinfractor;
    }
    
    public void setComedadinfractor(String comedadinfractor) {
        this.comedadinfractor = comedadinfractor;
    }
    public String getComdirinfractor() {
        return this.comdirinfractor;
    }
    
    public void setComdirinfractor(String comdirinfractor) {
        this.comdirinfractor = comdirinfractor;
    }
    public String getComemail() {
        return this.comemail;
    }
    
    public void setComemail(String comemail) {
        this.comemail = comemail;
    }
    public String getComteleinfractor() {
        return this.comteleinfractor;
    }
    
    public void setComteleinfractor(String comteleinfractor) {
        this.comteleinfractor = comteleinfractor;
    }
    public String getComidciudad() {
        return this.comidciudad;
    }
    
    public void setComidciudad(String comidciudad) {
        this.comidciudad = comidciudad;
    }
    public String getComlicencia() {
        return this.comlicencia;
    }
    
    public void setComlicencia(String comlicencia) {
        this.comlicencia = comlicencia;
    }
    public String getComcategoria() {
        return this.comcategoria;
    }
    
    public void setComcategoria(String comcategoria) {
        this.comcategoria = comcategoria;
    }
    public String getComsecreexpide() {
        return this.comsecreexpide;
    }
    
    public void setComsecreexpide(String comsecreexpide) {
        this.comsecreexpide = comsecreexpide;
    }
    public String getComfechavence() {
        return this.comfechavence;
    }
    
    public void setComfechavence(String comfechavence) {
        this.comfechavence = comfechavence;
    }
    public String getComtipoinfrac() {
        return this.comtipoinfrac;
    }
    
    public void setComtipoinfrac(String comtipoinfrac) {
        this.comtipoinfrac = comtipoinfrac;
    }
    public String getComplictransito() {
        return this.complictransito;
    }
    
    public void setComplictransito(String complictransito) {
        this.complictransito = complictransito;
    }
    public String getComdivipolicen() {
        return this.comdivipolicen;
    }
    
    public void setComdivipolicen(String comdivipolicen) {
        this.comdivipolicen = comdivipolicen;
    }
    public String getComidentificacion() {
        return this.comidentificacion;
    }
    
    public void setComidentificacion(String comidentificacion) {
        this.comidentificacion = comidentificacion;
    }
    public String getComidtipodocprop() {
        return this.comidtipodocprop;
    }
    
    public void setComidtipodocprop(String comidtipodocprop) {
        this.comidtipodocprop = comidtipodocprop;
    }
    public String getComnombreprop() {
        return this.comnombreprop;
    }
    
    public void setComnombreprop(String comnombreprop) {
        this.comnombreprop = comnombreprop;
    }
    public String getComnombreempresa() {
        return this.comnombreempresa;
    }
    
    public void setComnombreempresa(String comnombreempresa) {
        this.comnombreempresa = comnombreempresa;
    }
    public String getComnitempresa() {
        return this.comnitempresa;
    }
    
    public void setComnitempresa(String comnitempresa) {
        this.comnitempresa = comnitempresa;
    }
    public String getComtarjetaoperacion() {
        return this.comtarjetaoperacion;
    }
    
    public void setComtarjetaoperacion(String comtarjetaoperacion) {
        this.comtarjetaoperacion = comtarjetaoperacion;
    }
    public String getCompplacaagente() {
        return this.compplacaagente;
    }
    
    public void setCompplacaagente(String compplacaagente) {
        this.compplacaagente = compplacaagente;
    }
    public String getComobserva() {
        return this.comobserva;
    }
    
    public void setComobserva(String comobserva) {
        this.comobserva = comobserva;
    }
    public String getComfuga() {
        return this.comfuga;
    }
    
    public void setComfuga(String comfuga) {
        this.comfuga = comfuga;
    }
    public String getComacci() {
        return this.comacci;
    }
    
    public void setComacci(String comacci) {
        this.comacci = comacci;
    }
    public String getCominmov() {
        return this.cominmov;
    }
    
    public void setCominmov(String cominmov) {
        this.cominmov = cominmov;
    }
    public String getCompatioinmoviliza() {
        return this.compatioinmoviliza;
    }
    
    public void setCompatioinmoviliza(String compatioinmoviliza) {
        this.compatioinmoviliza = compatioinmoviliza;
    }
    public String getComdirpatioinmovi() {
        return this.comdirpatioinmovi;
    }
    
    public void setComdirpatioinmovi(String comdirpatioinmovi) {
        this.comdirpatioinmovi = comdirpatioinmovi;
    }
    public String getComgruanumero() {
        return this.comgruanumero;
    }
    
    public void setComgruanumero(String comgruanumero) {
        this.comgruanumero = comgruanumero;
    }
    public String getComplacagrua() {
        return this.complacagrua;
    }
    
    public void setComplacagrua(String complacagrua) {
        this.complacagrua = complacagrua;
    }
    public String getComconsecutiinmovi() {
        return this.comconsecutiinmovi;
    }
    
    public void setComconsecutiinmovi(String comconsecutiinmovi) {
        this.comconsecutiinmovi = comconsecutiinmovi;
    }
    public String getComidentificaciontest() {
        return this.comidentificaciontest;
    }
    
    public void setComidentificaciontest(String comidentificaciontest) {
        this.comidentificaciontest = comidentificaciontest;
    }
    public String getComnombretesti() {
        return this.comnombretesti;
    }
    
    public void setComnombretesti(String comnombretesti) {
        this.comnombretesti = comnombretesti;
    }
    public String getComdirecrestesti() {
        return this.comdirecrestesti;
    }
    
    public void setComdirecrestesti(String comdirecrestesti) {
        this.comdirecrestesti = comdirecrestesti;
    }
    public String getComteletestigo() {
        return this.comteletestigo;
    }
    
    public void setComteletestigo(String comteletestigo) {
        this.comteletestigo = comteletestigo;
    }
    public String getComvalor() {
        return this.comvalor;
    }
    
    public void setComvalor(String comvalor) {
        this.comvalor = comvalor;
    }
    public String getComvalad() {
        return this.comvalad;
    }
    
    public void setComvalad(String comvalad) {
        this.comvalad = comvalad;
    }
    public String getComorganismo() {
        return this.comorganismo;
    }
    
    public void setComorganismo(String comorganismo) {
        this.comorganismo = comorganismo;
    }
    public String getComestadocom() {
        return this.comestadocom;
    }
    
    public void setComestadocom(String comestadocom) {
        this.comestadocom = comestadocom;
    }
    public String getCompolca() {
        return this.compolca;
    }
    
    public void setCompolca(String compolca) {
        this.compolca = compolca;
    }
    public String getCominfraccion() {
        return this.cominfraccion;
    }
    
    public void setCominfraccion(String cominfraccion) {
        this.cominfraccion = cominfraccion;
    }
    public String getComvalinfra() {
        return this.comvalinfra;
    }
    
    public void setComvalinfra(String comvalinfra) {
        this.comvalinfra = comvalinfra;
    }
    public String getGradoalcohol() {
        return this.gradoalcohol;
    }
    
    public void setGradoalcohol(String gradoalcohol) {
        this.gradoalcohol = gradoalcohol;
    }
    public String getFotomulta() {
        return this.fotomulta;
    }
    
    public void setFotomulta(String fotomulta) {
        this.fotomulta = fotomulta;
    }
    public String getFechaDeNotificacion() {
        return this.fechaDeNotificacion;
    }
    
    public void setFechaDeNotificacion(String fechaDeNotificacion) {
        this.fechaDeNotificacion = fechaDeNotificacion;
    }
    public BigDecimal getEstado() {
        return this.estado;
    }
    
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }
    public Date getFechaProceso() {
        return this.fechaProceso;
    }
    
    public void setFechaProceso(Date fechaProceso) {
        this.fechaProceso = fechaProceso;
    }
    public String getDescripcionError() {
        return this.descripcionError;
    }
    
    public void setDescripcionError(String descripcionError) {
        this.descripcionError = descripcionError;
    }
    public BigDecimal getCarplaId() {
        return this.carplaId;
    }
    
    public void setCarplaId(BigDecimal carplaId) {
        this.carplaId = carplaId;
    }




}


