package com.contravenciones.tr.persistence;
// Generated 1/02/2018 01:51:55 PM by Hibernate Tools 4.3.1



/**
 * CivDetalleRecUsu generated by hbm2java
 */
public class CivDetalleRecUsu  implements java.io.Serializable {


     private CivDetalleRecUsuId id;
     private CivUsuarios civUsuarios;
     private CivRecursos civRecursos;
     private CivDetalleRecursos civDetalleRecursos;

    public CivDetalleRecUsu() {
    }

    public CivDetalleRecUsu(CivDetalleRecUsuId id, CivUsuarios civUsuarios, CivRecursos civRecursos, CivDetalleRecursos civDetalleRecursos) {
       this.id = id;
       this.civUsuarios = civUsuarios;
       this.civRecursos = civRecursos;
       this.civDetalleRecursos = civDetalleRecursos;
    }
   
    public CivDetalleRecUsuId getId() {
        return this.id;
    }
    
    public void setId(CivDetalleRecUsuId id) {
        this.id = id;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public CivRecursos getCivRecursos() {
        return this.civRecursos;
    }
    
    public void setCivRecursos(CivRecursos civRecursos) {
        this.civRecursos = civRecursos;
    }
    public CivDetalleRecursos getCivDetalleRecursos() {
        return this.civDetalleRecursos;
    }
    
    public void setCivDetalleRecursos(CivDetalleRecursos civDetalleRecursos) {
        this.civDetalleRecursos = civDetalleRecursos;
    }




}


