package com.contravenciones.tr.persistence;
// Generated 15/01/2018 03:21:52 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivDetalleRecUsu generated by hbm2java
 */
public class CivDetalleRecUsu  implements java.io.Serializable {


     private BigDecimal detRecId;
     private CivRecursos civRecursos;
     private CivUsuarios civUsuarios;
     private BigDecimal detRecUsuId;
     private Boolean propiedadVisible;
     private Boolean propiedadEnabled;
     private Date fechaInicial;
     private Date fechaFin;

    public CivDetalleRecUsu() {
    }

	
    public CivDetalleRecUsu(BigDecimal detRecId, CivRecursos civRecursos, CivUsuarios civUsuarios) {
        this.detRecId = detRecId;
        this.civRecursos = civRecursos;
        this.civUsuarios = civUsuarios;
    }
    public CivDetalleRecUsu(BigDecimal detRecId, CivRecursos civRecursos, CivUsuarios civUsuarios, BigDecimal detRecUsuId, Boolean propiedadVisible, Boolean propiedadEnabled, Date fechaInicial, Date fechaFin) {
       this.detRecId = detRecId;
       this.civRecursos = civRecursos;
       this.civUsuarios = civUsuarios;
       this.detRecUsuId = detRecUsuId;
       this.propiedadVisible = propiedadVisible;
       this.propiedadEnabled = propiedadEnabled;
       this.fechaInicial = fechaInicial;
       this.fechaFin = fechaFin;
    }
   
    public BigDecimal getDetRecId() {
        return this.detRecId;
    }
    
    public void setDetRecId(BigDecimal detRecId) {
        this.detRecId = detRecId;
    }
    public CivRecursos getCivRecursos() {
        return this.civRecursos;
    }
    
    public void setCivRecursos(CivRecursos civRecursos) {
        this.civRecursos = civRecursos;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public BigDecimal getDetRecUsuId() {
        return this.detRecUsuId;
    }
    
    public void setDetRecUsuId(BigDecimal detRecUsuId) {
        this.detRecUsuId = detRecUsuId;
    }
    public Boolean getPropiedadVisible() {
        return this.propiedadVisible;
    }
    
    public void setPropiedadVisible(Boolean propiedadVisible) {
        this.propiedadVisible = propiedadVisible;
    }
    public Boolean getPropiedadEnabled() {
        return this.propiedadEnabled;
    }
    
    public void setPropiedadEnabled(Boolean propiedadEnabled) {
        this.propiedadEnabled = propiedadEnabled;
    }
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


