package com.contravenciones.tr.persistence;
// Generated 1/02/2018 01:51:55 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivDetalleRecUsuId generated by hbm2java
 */
public class CivDetalleRecUsuId  implements java.io.Serializable {


     private BigDecimal recId;
     private BigDecimal usuId;
     private Boolean propiedadVisible;
     private Boolean propiedadEnabled;
     private BigDecimal detRecId;
     private Date fechaInicial;
     private Date fechaFin;

    public CivDetalleRecUsuId() {
    }

	
    public CivDetalleRecUsuId(BigDecimal recId, BigDecimal usuId, BigDecimal detRecId) {
        this.recId = recId;
        this.usuId = usuId;
        this.detRecId = detRecId;
    }
    public CivDetalleRecUsuId(BigDecimal recId, BigDecimal usuId, Boolean propiedadVisible, Boolean propiedadEnabled, BigDecimal detRecId, Date fechaInicial, Date fechaFin) {
       this.recId = recId;
       this.usuId = usuId;
       this.propiedadVisible = propiedadVisible;
       this.propiedadEnabled = propiedadEnabled;
       this.detRecId = detRecId;
       this.fechaInicial = fechaInicial;
       this.fechaFin = fechaFin;
    }
   
    public BigDecimal getRecId() {
        return this.recId;
    }
    
    public void setRecId(BigDecimal recId) {
        this.recId = recId;
    }
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }
    public Boolean getPropiedadVisible() {
        return this.propiedadVisible;
    }
    
    public void setPropiedadVisible(Boolean propiedadVisible) {
        this.propiedadVisible = propiedadVisible;
    }
    public Boolean getPropiedadEnabled() {
        return this.propiedadEnabled;
    }
    
    public void setPropiedadEnabled(Boolean propiedadEnabled) {
        this.propiedadEnabled = propiedadEnabled;
    }
    public BigDecimal getDetRecId() {
        return this.detRecId;
    }
    
    public void setDetRecId(BigDecimal detRecId) {
        this.detRecId = detRecId;
    }
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CivDetalleRecUsuId) ) return false;
		 CivDetalleRecUsuId castOther = ( CivDetalleRecUsuId ) other; 
         
		 return ( (this.getRecId()==castOther.getRecId()) || ( this.getRecId()!=null && castOther.getRecId()!=null && this.getRecId().equals(castOther.getRecId()) ) )
 && ( (this.getUsuId()==castOther.getUsuId()) || ( this.getUsuId()!=null && castOther.getUsuId()!=null && this.getUsuId().equals(castOther.getUsuId()) ) )
 && ( (this.getPropiedadVisible()==castOther.getPropiedadVisible()) || ( this.getPropiedadVisible()!=null && castOther.getPropiedadVisible()!=null && this.getPropiedadVisible().equals(castOther.getPropiedadVisible()) ) )
 && ( (this.getPropiedadEnabled()==castOther.getPropiedadEnabled()) || ( this.getPropiedadEnabled()!=null && castOther.getPropiedadEnabled()!=null && this.getPropiedadEnabled().equals(castOther.getPropiedadEnabled()) ) )
 && ( (this.getDetRecId()==castOther.getDetRecId()) || ( this.getDetRecId()!=null && castOther.getDetRecId()!=null && this.getDetRecId().equals(castOther.getDetRecId()) ) )
 && ( (this.getFechaInicial()==castOther.getFechaInicial()) || ( this.getFechaInicial()!=null && castOther.getFechaInicial()!=null && this.getFechaInicial().equals(castOther.getFechaInicial()) ) )
 && ( (this.getFechaFin()==castOther.getFechaFin()) || ( this.getFechaFin()!=null && castOther.getFechaFin()!=null && this.getFechaFin().equals(castOther.getFechaFin()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRecId() == null ? 0 : this.getRecId().hashCode() );
         result = 37 * result + ( getUsuId() == null ? 0 : this.getUsuId().hashCode() );
         result = 37 * result + ( getPropiedadVisible() == null ? 0 : this.getPropiedadVisible().hashCode() );
         result = 37 * result + ( getPropiedadEnabled() == null ? 0 : this.getPropiedadEnabled().hashCode() );
         result = 37 * result + ( getDetRecId() == null ? 0 : this.getDetRecId().hashCode() );
         result = 37 * result + ( getFechaInicial() == null ? 0 : this.getFechaInicial().hashCode() );
         result = 37 * result + ( getFechaFin() == null ? 0 : this.getFechaFin().hashCode() );
         return result;
   }   


}


