package com.contravenciones.tr.persistence;
// Generated 5/02/2018 01:39:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CivDetalleRecursos generated by hbm2java
 */
public class CivDetalleRecursos  implements java.io.Serializable {


     private BigDecimal detRecId;
     private CivRecursos civRecursos;
     private String detRecDescripcion;
     private String detRecObjeto;
     private String detRecTipo;
     private Set civDetalleRecUsus = new HashSet(0);

    public CivDetalleRecursos() {
    }

	
    public CivDetalleRecursos(BigDecimal detRecId) {
        this.detRecId = detRecId;
    }
    public CivDetalleRecursos(BigDecimal detRecId, CivRecursos civRecursos, String detRecDescripcion, String detRecObjeto, String detRecTipo, Set civDetalleRecUsus) {
       this.detRecId = detRecId;
       this.civRecursos = civRecursos;
       this.detRecDescripcion = detRecDescripcion;
       this.detRecObjeto = detRecObjeto;
       this.detRecTipo = detRecTipo;
       this.civDetalleRecUsus = civDetalleRecUsus;
    }
   
    public BigDecimal getDetRecId() {
        return this.detRecId;
    }
    
    public void setDetRecId(BigDecimal detRecId) {
        this.detRecId = detRecId;
    }
    public CivRecursos getCivRecursos() {
        return this.civRecursos;
    }
    
    public void setCivRecursos(CivRecursos civRecursos) {
        this.civRecursos = civRecursos;
    }
    public String getDetRecDescripcion() {
        return this.detRecDescripcion;
    }
    
    public void setDetRecDescripcion(String detRecDescripcion) {
        this.detRecDescripcion = detRecDescripcion;
    }
    public String getDetRecObjeto() {
        return this.detRecObjeto;
    }
    
    public void setDetRecObjeto(String detRecObjeto) {
        this.detRecObjeto = detRecObjeto;
    }
    public String getDetRecTipo() {
        return this.detRecTipo;
    }
    
    public void setDetRecTipo(String detRecTipo) {
        this.detRecTipo = detRecTipo;
    }
    public Set getCivDetalleRecUsus() {
        return this.civDetalleRecUsus;
    }
    
    public void setCivDetalleRecUsus(Set civDetalleRecUsus) {
        this.civDetalleRecUsus = civDetalleRecUsus;
    }




}


