package com.contravenciones.tr.persistence;
// Generated 5/02/2018 01:39:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CivDivipos generated by hbm2java
 */
public class CivDivipos  implements java.io.Serializable {


     private BigDecimal divId;
     private CivPoblados civPoblados;
     private CivPais civPais;
     private CivMunicipios civMunicipios;
     private CivDepartamentos civDepartamentos;
     private BigDecimal divCodigo;
     private Set civDireccioneses = new HashSet(0);

    public CivDivipos() {
    }

	
    public CivDivipos(BigDecimal divId) {
        this.divId = divId;
    }
    public CivDivipos(BigDecimal divId, CivPoblados civPoblados, CivPais civPais, CivMunicipios civMunicipios, CivDepartamentos civDepartamentos, BigDecimal divCodigo, Set civDireccioneses) {
       this.divId = divId;
       this.civPoblados = civPoblados;
       this.civPais = civPais;
       this.civMunicipios = civMunicipios;
       this.civDepartamentos = civDepartamentos;
       this.divCodigo = divCodigo;
       this.civDireccioneses = civDireccioneses;
    }
   
    public BigDecimal getDivId() {
        return this.divId;
    }
    
    public void setDivId(BigDecimal divId) {
        this.divId = divId;
    }
    public CivPoblados getCivPoblados() {
        return this.civPoblados;
    }
    
    public void setCivPoblados(CivPoblados civPoblados) {
        this.civPoblados = civPoblados;
    }
    public CivPais getCivPais() {
        return this.civPais;
    }
    
    public void setCivPais(CivPais civPais) {
        this.civPais = civPais;
    }
    public CivMunicipios getCivMunicipios() {
        return this.civMunicipios;
    }
    
    public void setCivMunicipios(CivMunicipios civMunicipios) {
        this.civMunicipios = civMunicipios;
    }
    public CivDepartamentos getCivDepartamentos() {
        return this.civDepartamentos;
    }
    
    public void setCivDepartamentos(CivDepartamentos civDepartamentos) {
        this.civDepartamentos = civDepartamentos;
    }
    public BigDecimal getDivCodigo() {
        return this.divCodigo;
    }
    
    public void setDivCodigo(BigDecimal divCodigo) {
        this.divCodigo = divCodigo;
    }
    public Set getCivDireccioneses() {
        return this.civDireccioneses;
    }
    
    public void setCivDireccioneses(Set civDireccioneses) {
        this.civDireccioneses = civDireccioneses;
    }




}


