package com.contravenciones.tr.persistence;
// Generated 15/01/2018 11:03:58 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivDetallecartera generated by hbm2java
 */
public class CivDetallecartera  implements java.io.Serializable {


     private BigDecimal detcarId;
     private CivUsuarios civUsuarios;
     private CivCarteras civCarteras;
     private CivConceptos civConceptos;
     private String detcarReferencia;
     private Date detcarFecha;
     private byte detcarEstado;
     private BigDecimal detcarValor;
     private BigDecimal pagId;

    public CivDetallecartera() {
    }

	
    public CivDetallecartera(BigDecimal detcarId, CivUsuarios civUsuarios, CivCarteras civCarteras, CivConceptos civConceptos, String detcarReferencia, Date detcarFecha, byte detcarEstado, BigDecimal detcarValor) {
        this.detcarId = detcarId;
        this.civUsuarios = civUsuarios;
        this.civCarteras = civCarteras;
        this.civConceptos = civConceptos;
        this.detcarReferencia = detcarReferencia;
        this.detcarFecha = detcarFecha;
        this.detcarEstado = detcarEstado;
        this.detcarValor = detcarValor;
    }
    public CivDetallecartera(BigDecimal detcarId, CivUsuarios civUsuarios, CivCarteras civCarteras, CivConceptos civConceptos, String detcarReferencia, Date detcarFecha, byte detcarEstado, BigDecimal detcarValor, BigDecimal pagId) {
       this.detcarId = detcarId;
       this.civUsuarios = civUsuarios;
       this.civCarteras = civCarteras;
       this.civConceptos = civConceptos;
       this.detcarReferencia = detcarReferencia;
       this.detcarFecha = detcarFecha;
       this.detcarEstado = detcarEstado;
       this.detcarValor = detcarValor;
       this.pagId = pagId;
    }
   
    public BigDecimal getDetcarId() {
        return this.detcarId;
    }
    
    public void setDetcarId(BigDecimal detcarId) {
        this.detcarId = detcarId;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public CivCarteras getCivCarteras() {
        return this.civCarteras;
    }
    
    public void setCivCarteras(CivCarteras civCarteras) {
        this.civCarteras = civCarteras;
    }
    public CivConceptos getCivConceptos() {
        return this.civConceptos;
    }
    
    public void setCivConceptos(CivConceptos civConceptos) {
        this.civConceptos = civConceptos;
    }
    public String getDetcarReferencia() {
        return this.detcarReferencia;
    }
    
    public void setDetcarReferencia(String detcarReferencia) {
        this.detcarReferencia = detcarReferencia;
    }
    public Date getDetcarFecha() {
        return this.detcarFecha;
    }
    
    public void setDetcarFecha(Date detcarFecha) {
        this.detcarFecha = detcarFecha;
    }
    public byte getDetcarEstado() {
        return this.detcarEstado;
    }
    
    public void setDetcarEstado(byte detcarEstado) {
        this.detcarEstado = detcarEstado;
    }
    public BigDecimal getDetcarValor() {
        return this.detcarValor;
    }
    
    public void setDetcarValor(BigDecimal detcarValor) {
        this.detcarValor = detcarValor;
    }
    public BigDecimal getPagId() {
        return this.pagId;
    }
    
    public void setPagId(BigDecimal pagId) {
        this.pagId = pagId;
    }




}


