package com.contravenciones.tr.persistence;
// Generated 1/02/2018 01:51:55 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivDetallecartera generated by hbm2java
 */
public class CivDetallecartera  implements java.io.Serializable {


     private BigDecimal detcarId;
     private CivConceptos civConceptos;
     private CivCarteras civCarteras;
     private String detcarReferencia;
     private Date detcarFecha;
     private byte detcarEstado;
     private BigDecimal detcarValor;

    public CivDetallecartera() {
    }

    public CivDetallecartera(BigDecimal detcarId, CivConceptos civConceptos, CivCarteras civCarteras, String detcarReferencia, Date detcarFecha, byte detcarEstado, BigDecimal detcarValor) {
       this.detcarId = detcarId;
       this.civConceptos = civConceptos;
       this.civCarteras = civCarteras;
       this.detcarReferencia = detcarReferencia;
       this.detcarFecha = detcarFecha;
       this.detcarEstado = detcarEstado;
       this.detcarValor = detcarValor;
    }
   
    public BigDecimal getDetcarId() {
        return this.detcarId;
    }
    
    public void setDetcarId(BigDecimal detcarId) {
        this.detcarId = detcarId;
    }
    public CivConceptos getCivConceptos() {
        return this.civConceptos;
    }
    
    public void setCivConceptos(CivConceptos civConceptos) {
        this.civConceptos = civConceptos;
    }
    public CivCarteras getCivCarteras() {
        return this.civCarteras;
    }
    
    public void setCivCarteras(CivCarteras civCarteras) {
        this.civCarteras = civCarteras;
    }
    public String getDetcarReferencia() {
        return this.detcarReferencia;
    }
    
    public void setDetcarReferencia(String detcarReferencia) {
        this.detcarReferencia = detcarReferencia;
    }
    public Date getDetcarFecha() {
        return this.detcarFecha;
    }
    
    public void setDetcarFecha(Date detcarFecha) {
        this.detcarFecha = detcarFecha;
    }
    public byte getDetcarEstado() {
        return this.detcarEstado;
    }
    
    public void setDetcarEstado(byte detcarEstado) {
        this.detcarEstado = detcarEstado;
    }
    public BigDecimal getDetcarValor() {
        return this.detcarValor;
    }
    
    public void setDetcarValor(BigDecimal detcarValor) {
        this.detcarValor = detcarValor;
    }




}


