package com.contravenciones.tr.persistence;
// Generated 5/02/2018 01:39:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CivDescuentos generated by hbm2java
 */
public class CivDescuentos  implements java.io.Serializable {


     private BigDecimal desId;
     private CivResoluciones civResoluciones;

    public CivDescuentos() {
    }

    public CivDescuentos(BigDecimal desId, CivResoluciones civResoluciones) {
       this.desId = desId;
       this.civResoluciones = civResoluciones;
    }
   
    public BigDecimal getDesId() {
        return this.desId;
    }
    
    public void setDesId(BigDecimal desId) {
        this.desId = desId;
    }
    public CivResoluciones getCivResoluciones() {
        return this.civResoluciones;
    }
    
    public void setCivResoluciones(CivResoluciones civResoluciones) {
        this.civResoluciones = civResoluciones;
    }




}


