package com.contravenciones.tr.persistence;
// Generated 1/02/2018 01:51:55 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivExpedientes generated by hbm2java
 */
public class CivExpedientes  implements java.io.Serializable {


     private BigDecimal expId;
     private CivPersonas civPersonas;
     private String expNumero;
     private BigDecimal expEstado;
     private Date expFecha;
     private BigDecimal expTipo;
     private Set civComparendoses = new HashSet(0);
     private Set civResolucioneses = new HashSet(0);

    public CivExpedientes() {
    }

	
    public CivExpedientes(BigDecimal expId, CivPersonas civPersonas, String expNumero, BigDecimal expEstado, Date expFecha, BigDecimal expTipo) {
        this.expId = expId;
        this.civPersonas = civPersonas;
        this.expNumero = expNumero;
        this.expEstado = expEstado;
        this.expFecha = expFecha;
        this.expTipo = expTipo;
    }
    public CivExpedientes(BigDecimal expId, CivPersonas civPersonas, String expNumero, BigDecimal expEstado, Date expFecha, BigDecimal expTipo, Set civComparendoses, Set civResolucioneses) {
       this.expId = expId;
       this.civPersonas = civPersonas;
       this.expNumero = expNumero;
       this.expEstado = expEstado;
       this.expFecha = expFecha;
       this.expTipo = expTipo;
       this.civComparendoses = civComparendoses;
       this.civResolucioneses = civResolucioneses;
    }
   
    public BigDecimal getExpId() {
        return this.expId;
    }
    
    public void setExpId(BigDecimal expId) {
        this.expId = expId;
    }
    public CivPersonas getCivPersonas() {
        return this.civPersonas;
    }
    
    public void setCivPersonas(CivPersonas civPersonas) {
        this.civPersonas = civPersonas;
    }
    public String getExpNumero() {
        return this.expNumero;
    }
    
    public void setExpNumero(String expNumero) {
        this.expNumero = expNumero;
    }
    public BigDecimal getExpEstado() {
        return this.expEstado;
    }
    
    public void setExpEstado(BigDecimal expEstado) {
        this.expEstado = expEstado;
    }
    public Date getExpFecha() {
        return this.expFecha;
    }
    
    public void setExpFecha(Date expFecha) {
        this.expFecha = expFecha;
    }
    public BigDecimal getExpTipo() {
        return this.expTipo;
    }
    
    public void setExpTipo(BigDecimal expTipo) {
        this.expTipo = expTipo;
    }
    public Set getCivComparendoses() {
        return this.civComparendoses;
    }
    
    public void setCivComparendoses(Set civComparendoses) {
        this.civComparendoses = civComparendoses;
    }
    public Set getCivResolucioneses() {
        return this.civResolucioneses;
    }
    
    public void setCivResolucioneses(Set civResolucioneses) {
        this.civResolucioneses = civResolucioneses;
    }




}


