package com.contravenciones.tr.persistence;
// Generated 1/02/2018 01:51:55 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CivMunicipios generated by hbm2java
 */
public class CivMunicipios  implements java.io.Serializable {


     private BigDecimal munId;
     private CivPais civPais;
     private String munNombre;
     private BigDecimal munCodmunicipio;
     private BigDecimal depId;
     private Set civPobladoses = new HashSet(0);
     private Set civDiviposes = new HashSet(0);

    public CivMunicipios() {
    }

	
    public CivMunicipios(BigDecimal munId) {
        this.munId = munId;
    }
    public CivMunicipios(BigDecimal munId, CivPais civPais, String munNombre, BigDecimal munCodmunicipio, BigDecimal depId, Set civPobladoses, Set civDiviposes) {
       this.munId = munId;
       this.civPais = civPais;
       this.munNombre = munNombre;
       this.munCodmunicipio = munCodmunicipio;
       this.depId = depId;
       this.civPobladoses = civPobladoses;
       this.civDiviposes = civDiviposes;
    }
   
    public BigDecimal getMunId() {
        return this.munId;
    }
    
    public void setMunId(BigDecimal munId) {
        this.munId = munId;
    }
    public CivPais getCivPais() {
        return this.civPais;
    }
    
    public void setCivPais(CivPais civPais) {
        this.civPais = civPais;
    }
    public String getMunNombre() {
        return this.munNombre;
    }
    
    public void setMunNombre(String munNombre) {
        this.munNombre = munNombre;
    }
    public BigDecimal getMunCodmunicipio() {
        return this.munCodmunicipio;
    }
    
    public void setMunCodmunicipio(BigDecimal munCodmunicipio) {
        this.munCodmunicipio = munCodmunicipio;
    }
    public BigDecimal getDepId() {
        return this.depId;
    }
    
    public void setDepId(BigDecimal depId) {
        this.depId = depId;
    }
    public Set getCivPobladoses() {
        return this.civPobladoses;
    }
    
    public void setCivPobladoses(Set civPobladoses) {
        this.civPobladoses = civPobladoses;
    }
    public Set getCivDiviposes() {
        return this.civDiviposes;
    }
    
    public void setCivDiviposes(Set civDiviposes) {
        this.civDiviposes = civDiviposes;
    }




}


