package com.contravenciones.tr.persistence;
// Generated 1/02/2018 01:51:55 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivPerfilrecursoId generated by hbm2java
 */
public class CivPerfilrecursoId  implements java.io.Serializable {


     private Date perrecFechaini;
     private Date perrecFechafin;
     private BigDecimal recId;
     private BigDecimal usuId;

    public CivPerfilrecursoId() {
    }

	
    public CivPerfilrecursoId(BigDecimal recId) {
        this.recId = recId;
    }
    public CivPerfilrecursoId(Date perrecFechaini, Date perrecFechafin, BigDecimal recId, BigDecimal usuId) {
       this.perrecFechaini = perrecFechaini;
       this.perrecFechafin = perrecFechafin;
       this.recId = recId;
       this.usuId = usuId;
    }
   
    public Date getPerrecFechaini() {
        return this.perrecFechaini;
    }
    
    public void setPerrecFechaini(Date perrecFechaini) {
        this.perrecFechaini = perrecFechaini;
    }
    public Date getPerrecFechafin() {
        return this.perrecFechafin;
    }
    
    public void setPerrecFechafin(Date perrecFechafin) {
        this.perrecFechafin = perrecFechafin;
    }
    public BigDecimal getRecId() {
        return this.recId;
    }
    
    public void setRecId(BigDecimal recId) {
        this.recId = recId;
    }
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CivPerfilrecursoId) ) return false;
		 CivPerfilrecursoId castOther = ( CivPerfilrecursoId ) other; 
         
		 return ( (this.getPerrecFechaini()==castOther.getPerrecFechaini()) || ( this.getPerrecFechaini()!=null && castOther.getPerrecFechaini()!=null && this.getPerrecFechaini().equals(castOther.getPerrecFechaini()) ) )
 && ( (this.getPerrecFechafin()==castOther.getPerrecFechafin()) || ( this.getPerrecFechafin()!=null && castOther.getPerrecFechafin()!=null && this.getPerrecFechafin().equals(castOther.getPerrecFechafin()) ) )
 && ( (this.getRecId()==castOther.getRecId()) || ( this.getRecId()!=null && castOther.getRecId()!=null && this.getRecId().equals(castOther.getRecId()) ) )
 && ( (this.getUsuId()==castOther.getUsuId()) || ( this.getUsuId()!=null && castOther.getUsuId()!=null && this.getUsuId().equals(castOther.getUsuId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPerrecFechaini() == null ? 0 : this.getPerrecFechaini().hashCode() );
         result = 37 * result + ( getPerrecFechafin() == null ? 0 : this.getPerrecFechafin().hashCode() );
         result = 37 * result + ( getRecId() == null ? 0 : this.getRecId().hashCode() );
         result = 37 * result + ( getUsuId() == null ? 0 : this.getUsuId().hashCode() );
         return result;
   }   


}


