package com.contravenciones.tr.persistence;
// Generated 1/02/2018 01:51:55 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CivPoblados generated by hbm2java
 */
public class CivPoblados  implements java.io.Serializable {


     private BigDecimal pobId;
     private CivMunicipios civMunicipios;
     private String pobNombre;
     private BigDecimal pobCodpoblado;
     private Set civDiviposes = new HashSet(0);

    public CivPoblados() {
    }

	
    public CivPoblados(BigDecimal pobId) {
        this.pobId = pobId;
    }
    public CivPoblados(BigDecimal pobId, CivMunicipios civMunicipios, String pobNombre, BigDecimal pobCodpoblado, Set civDiviposes) {
       this.pobId = pobId;
       this.civMunicipios = civMunicipios;
       this.pobNombre = pobNombre;
       this.pobCodpoblado = pobCodpoblado;
       this.civDiviposes = civDiviposes;
    }
   
    public BigDecimal getPobId() {
        return this.pobId;
    }
    
    public void setPobId(BigDecimal pobId) {
        this.pobId = pobId;
    }
    public CivMunicipios getCivMunicipios() {
        return this.civMunicipios;
    }
    
    public void setCivMunicipios(CivMunicipios civMunicipios) {
        this.civMunicipios = civMunicipios;
    }
    public String getPobNombre() {
        return this.pobNombre;
    }
    
    public void setPobNombre(String pobNombre) {
        this.pobNombre = pobNombre;
    }
    public BigDecimal getPobCodpoblado() {
        return this.pobCodpoblado;
    }
    
    public void setPobCodpoblado(BigDecimal pobCodpoblado) {
        this.pobCodpoblado = pobCodpoblado;
    }
    public Set getCivDiviposes() {
        return this.civDiviposes;
    }
    
    public void setCivDiviposes(Set civDiviposes) {
        this.civDiviposes = civDiviposes;
    }




}


