package com.contravenciones.tr.persistence;
// Generated 5/02/2018 01:39:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CivPais generated by hbm2java
 */
public class CivPais  implements java.io.Serializable {


     private BigDecimal paiId;
     private String paiNombre;
     private BigDecimal paiCodpais;
     private Set civMunicipioses = new HashSet(0);
     private Set civDepartamentoses = new HashSet(0);
     private Set civDiviposes = new HashSet(0);

    public CivPais() {
    }

	
    public CivPais(BigDecimal paiId) {
        this.paiId = paiId;
    }
    public CivPais(BigDecimal paiId, String paiNombre, BigDecimal paiCodpais, Set civMunicipioses, Set civDepartamentoses, Set civDiviposes) {
       this.paiId = paiId;
       this.paiNombre = paiNombre;
       this.paiCodpais = paiCodpais;
       this.civMunicipioses = civMunicipioses;
       this.civDepartamentoses = civDepartamentoses;
       this.civDiviposes = civDiviposes;
    }
   
    public BigDecimal getPaiId() {
        return this.paiId;
    }
    
    public void setPaiId(BigDecimal paiId) {
        this.paiId = paiId;
    }
    public String getPaiNombre() {
        return this.paiNombre;
    }
    
    public void setPaiNombre(String paiNombre) {
        this.paiNombre = paiNombre;
    }
    public BigDecimal getPaiCodpais() {
        return this.paiCodpais;
    }
    
    public void setPaiCodpais(BigDecimal paiCodpais) {
        this.paiCodpais = paiCodpais;
    }
    public Set getCivMunicipioses() {
        return this.civMunicipioses;
    }
    
    public void setCivMunicipioses(Set civMunicipioses) {
        this.civMunicipioses = civMunicipioses;
    }
    public Set getCivDepartamentoses() {
        return this.civDepartamentoses;
    }
    
    public void setCivDepartamentoses(Set civDepartamentoses) {
        this.civDepartamentoses = civDepartamentoses;
    }
    public Set getCivDiviposes() {
        return this.civDiviposes;
    }
    
    public void setCivDiviposes(Set civDiviposes) {
        this.civDiviposes = civDiviposes;
    }




}


