package com.contravenciones.tr.persistence;
// Generated 1/02/2018 01:51:55 PM by Hibernate Tools 4.3.1



/**
 * CivPerfilrecurso generated by hbm2java
 */
public class CivPerfilrecurso  implements java.io.Serializable {


     private CivPerfilrecursoId id;
     private CivUsuarios civUsuarios;
     private CivRecursos civRecursos;

    public CivPerfilrecurso() {
    }

	
    public CivPerfilrecurso(CivPerfilrecursoId id, CivRecursos civRecursos) {
        this.id = id;
        this.civRecursos = civRecursos;
    }
    public CivPerfilrecurso(CivPerfilrecursoId id, CivUsuarios civUsuarios, CivRecursos civRecursos) {
       this.id = id;
       this.civUsuarios = civUsuarios;
       this.civRecursos = civRecursos;
    }
   
    public CivPerfilrecursoId getId() {
        return this.id;
    }
    
    public void setId(CivPerfilrecursoId id) {
        this.id = id;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public CivRecursos getCivRecursos() {
        return this.civRecursos;
    }
    
    public void setCivRecursos(CivRecursos civRecursos) {
        this.civRecursos = civRecursos;
    }




}


