package com.contravenciones.tr.persistence;
// Generated 23/01/2018 03:51:28 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivRangosComparendos generated by hbm2java
 */
public class CivRangosComparendos  implements java.io.Serializable {


     private BigDecimal ranId;
     private String ranNumInicial;
     private String ranNumFinal;
     private Date ranFechaInicial;
     private Date ranFechaFinal;
     private BigDecimal ranEstado;
     private String ranNumResolucion;
     private Date ranFechaResolucion;
     private BigDecimal usuId;
     private BigDecimal ranTipoComparendo;
     private Set civDetalleRangoComparendoses = new HashSet(0);

    public CivRangosComparendos() {
    }

	
    public CivRangosComparendos(BigDecimal ranId) {
        this.ranId = ranId;
    }
    public CivRangosComparendos(BigDecimal ranId, String ranNumInicial, String ranNumFinal, Date ranFechaInicial, Date ranFechaFinal, BigDecimal ranEstado, String ranNumResolucion, Date ranFechaResolucion, BigDecimal usuId, BigDecimal ranTipoComparendo, Set civDetalleRangoComparendoses) {
       this.ranId = ranId;
       this.ranNumInicial = ranNumInicial;
       this.ranNumFinal = ranNumFinal;
       this.ranFechaInicial = ranFechaInicial;
       this.ranFechaFinal = ranFechaFinal;
       this.ranEstado = ranEstado;
       this.ranNumResolucion = ranNumResolucion;
       this.ranFechaResolucion = ranFechaResolucion;
       this.usuId = usuId;
       this.ranTipoComparendo = ranTipoComparendo;
       this.civDetalleRangoComparendoses = civDetalleRangoComparendoses;
    }
   
    public BigDecimal getRanId() {
        return this.ranId;
    }
    
    public void setRanId(BigDecimal ranId) {
        this.ranId = ranId;
    }
    public String getRanNumInicial() {
        return this.ranNumInicial;
    }
    
    public void setRanNumInicial(String ranNumInicial) {
        this.ranNumInicial = ranNumInicial;
    }
    public String getRanNumFinal() {
        return this.ranNumFinal;
    }
    
    public void setRanNumFinal(String ranNumFinal) {
        this.ranNumFinal = ranNumFinal;
    }
    public Date getRanFechaInicial() {
        return this.ranFechaInicial;
    }
    
    public void setRanFechaInicial(Date ranFechaInicial) {
        this.ranFechaInicial = ranFechaInicial;
    }
    public Date getRanFechaFinal() {
        return this.ranFechaFinal;
    }
    
    public void setRanFechaFinal(Date ranFechaFinal) {
        this.ranFechaFinal = ranFechaFinal;
    }
    public BigDecimal getRanEstado() {
        return this.ranEstado;
    }
    
    public void setRanEstado(BigDecimal ranEstado) {
        this.ranEstado = ranEstado;
    }
    public String getRanNumResolucion() {
        return this.ranNumResolucion;
    }
    
    public void setRanNumResolucion(String ranNumResolucion) {
        this.ranNumResolucion = ranNumResolucion;
    }
    public Date getRanFechaResolucion() {
        return this.ranFechaResolucion;
    }
    
    public void setRanFechaResolucion(Date ranFechaResolucion) {
        this.ranFechaResolucion = ranFechaResolucion;
    }
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }
    public BigDecimal getRanTipoComparendo() {
        return this.ranTipoComparendo;
    }
    
    public void setRanTipoComparendo(BigDecimal ranTipoComparendo) {
        this.ranTipoComparendo = ranTipoComparendo;
    }
    public Set getCivDetalleRangoComparendoses() {
        return this.civDetalleRangoComparendoses;
    }
    
    public void setCivDetalleRangoComparendoses(Set civDetalleRangoComparendoses) {
        this.civDetalleRangoComparendoses = civDetalleRangoComparendoses;
    }




}


