package com.contravenciones.tr.persistence;
// Generated 5/02/2018 01:39:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivResoluciones generated by hbm2java
 */
public class CivResoluciones  implements java.io.Serializable {


     private BigDecimal resId;
     private CivExpedientes civExpedientes;
     private CivCarteras civCarteras;
     private String resNumero;
     private Date resFecha;
     private String resNumAnterior;
     private BigDecimal resEstado;
     private Date resFechainicial;
     private Date resFechafinal;
     private Set civCobrocoactivos = new HashSet(0);
     private Set civDescuentoses = new HashSet(0);
     private Set civFinanciacioneses = new HashSet(0);
     private Set civSancioneses = new HashSet(0);

    public CivResoluciones() {
    }

	
    public CivResoluciones(BigDecimal resId, CivCarteras civCarteras, String resNumero, Date resFecha, BigDecimal resEstado, Date resFechainicial) {
        this.resId = resId;
        this.civCarteras = civCarteras;
        this.resNumero = resNumero;
        this.resFecha = resFecha;
        this.resEstado = resEstado;
        this.resFechainicial = resFechainicial;
    }
    public CivResoluciones(BigDecimal resId, CivExpedientes civExpedientes, CivCarteras civCarteras, String resNumero, Date resFecha, String resNumAnterior, BigDecimal resEstado, Date resFechainicial, Date resFechafinal, Set civCobrocoactivos, Set civDescuentoses, Set civFinanciacioneses, Set civSancioneses) {
       this.resId = resId;
       this.civExpedientes = civExpedientes;
       this.civCarteras = civCarteras;
       this.resNumero = resNumero;
       this.resFecha = resFecha;
       this.resNumAnterior = resNumAnterior;
       this.resEstado = resEstado;
       this.resFechainicial = resFechainicial;
       this.resFechafinal = resFechafinal;
       this.civCobrocoactivos = civCobrocoactivos;
       this.civDescuentoses = civDescuentoses;
       this.civFinanciacioneses = civFinanciacioneses;
       this.civSancioneses = civSancioneses;
    }
   
    public BigDecimal getResId() {
        return this.resId;
    }
    
    public void setResId(BigDecimal resId) {
        this.resId = resId;
    }
    public CivExpedientes getCivExpedientes() {
        return this.civExpedientes;
    }
    
    public void setCivExpedientes(CivExpedientes civExpedientes) {
        this.civExpedientes = civExpedientes;
    }
    public CivCarteras getCivCarteras() {
        return this.civCarteras;
    }
    
    public void setCivCarteras(CivCarteras civCarteras) {
        this.civCarteras = civCarteras;
    }
    public String getResNumero() {
        return this.resNumero;
    }
    
    public void setResNumero(String resNumero) {
        this.resNumero = resNumero;
    }
    public Date getResFecha() {
        return this.resFecha;
    }
    
    public void setResFecha(Date resFecha) {
        this.resFecha = resFecha;
    }
    public String getResNumAnterior() {
        return this.resNumAnterior;
    }
    
    public void setResNumAnterior(String resNumAnterior) {
        this.resNumAnterior = resNumAnterior;
    }
    public BigDecimal getResEstado() {
        return this.resEstado;
    }
    
    public void setResEstado(BigDecimal resEstado) {
        this.resEstado = resEstado;
    }
    public Date getResFechainicial() {
        return this.resFechainicial;
    }
    
    public void setResFechainicial(Date resFechainicial) {
        this.resFechainicial = resFechainicial;
    }
    public Date getResFechafinal() {
        return this.resFechafinal;
    }
    
    public void setResFechafinal(Date resFechafinal) {
        this.resFechafinal = resFechafinal;
    }
    public Set getCivCobrocoactivos() {
        return this.civCobrocoactivos;
    }
    
    public void setCivCobrocoactivos(Set civCobrocoactivos) {
        this.civCobrocoactivos = civCobrocoactivos;
    }
    public Set getCivDescuentoses() {
        return this.civDescuentoses;
    }
    
    public void setCivDescuentoses(Set civDescuentoses) {
        this.civDescuentoses = civDescuentoses;
    }
    public Set getCivFinanciacioneses() {
        return this.civFinanciacioneses;
    }
    
    public void setCivFinanciacioneses(Set civFinanciacioneses) {
        this.civFinanciacioneses = civFinanciacioneses;
    }
    public Set getCivSancioneses() {
        return this.civSancioneses;
    }
    
    public void setCivSancioneses(Set civSancioneses) {
        this.civSancioneses = civSancioneses;
    }




}


