package com.contravenciones.tr.persistence;
// Generated 5/02/2018 01:39:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivTipopagos generated by hbm2java
 */
public class CivTipopagos  implements java.io.Serializable {


     private BigDecimal tippagId;
     private String tipcarNombre;
     private BigDecimal tipcarEstado;
     private Date tipcarFechainicial;
     private Date tipcarFechafinal;
     private Set civUsuariosTipopagoses = new HashSet(0);

    public CivTipopagos() {
    }

	
    public CivTipopagos(BigDecimal tippagId, String tipcarNombre, Date tipcarFechainicial) {
        this.tippagId = tippagId;
        this.tipcarNombre = tipcarNombre;
        this.tipcarFechainicial = tipcarFechainicial;
    }
    public CivTipopagos(BigDecimal tippagId, String tipcarNombre, BigDecimal tipcarEstado, Date tipcarFechainicial, Date tipcarFechafinal, Set civUsuariosTipopagoses) {
       this.tippagId = tippagId;
       this.tipcarNombre = tipcarNombre;
       this.tipcarEstado = tipcarEstado;
       this.tipcarFechainicial = tipcarFechainicial;
       this.tipcarFechafinal = tipcarFechafinal;
       this.civUsuariosTipopagoses = civUsuariosTipopagoses;
    }
   
    public BigDecimal getTippagId() {
        return this.tippagId;
    }
    
    public void setTippagId(BigDecimal tippagId) {
        this.tippagId = tippagId;
    }
    public String getTipcarNombre() {
        return this.tipcarNombre;
    }
    
    public void setTipcarNombre(String tipcarNombre) {
        this.tipcarNombre = tipcarNombre;
    }
    public BigDecimal getTipcarEstado() {
        return this.tipcarEstado;
    }
    
    public void setTipcarEstado(BigDecimal tipcarEstado) {
        this.tipcarEstado = tipcarEstado;
    }
    public Date getTipcarFechainicial() {
        return this.tipcarFechainicial;
    }
    
    public void setTipcarFechainicial(Date tipcarFechainicial) {
        this.tipcarFechainicial = tipcarFechainicial;
    }
    public Date getTipcarFechafinal() {
        return this.tipcarFechafinal;
    }
    
    public void setTipcarFechafinal(Date tipcarFechafinal) {
        this.tipcarFechafinal = tipcarFechafinal;
    }
    public Set getCivUsuariosTipopagoses() {
        return this.civUsuariosTipopagoses;
    }
    
    public void setCivUsuariosTipopagoses(Set civUsuariosTipopagoses) {
        this.civUsuariosTipopagoses = civUsuariosTipopagoses;
    }




}


