package com.contravenciones.tr.persistence;
// Generated 1/02/2018 01:51:55 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivUsuarios generated by hbm2java
 */
public class CivUsuarios  implements java.io.Serializable {


     private BigDecimal usuId;
     private CivPersonas civPersonas;
     private String usuNombre;
     private String usuPassword;
     private BigDecimal usuEstado;
     private Date usuFechainicial;
     private Date usuFechafinal;
     private Date usuFechaproceso;
     private Set civUsuarioCajases = new HashSet(0);
     private Set logEventoses = new HashSet(0);
     private Set civUspHistorias = new HashSet(0);
     private Set civPerfilrecursos = new HashSet(0);
     private Set civUsuariosTipopagoses = new HashSet(0);
     private Set civDetalleRecUsus = new HashSet(0);
     private Set civValorinfraccions = new HashSet(0);
     private Set civAttemptses = new HashSet(0);

    public CivUsuarios() {
    }

	
    public CivUsuarios(BigDecimal usuId, CivPersonas civPersonas, String usuNombre, String usuPassword, BigDecimal usuEstado, Date usuFechainicial, Date usuFechaproceso) {
        this.usuId = usuId;
        this.civPersonas = civPersonas;
        this.usuNombre = usuNombre;
        this.usuPassword = usuPassword;
        this.usuEstado = usuEstado;
        this.usuFechainicial = usuFechainicial;
        this.usuFechaproceso = usuFechaproceso;
    }
    public CivUsuarios(BigDecimal usuId, CivPersonas civPersonas, String usuNombre, String usuPassword, BigDecimal usuEstado, Date usuFechainicial, Date usuFechafinal, Date usuFechaproceso, Set civUsuarioCajases, Set logEventoses, Set civUspHistorias, Set civPerfilrecursos, Set civUsuariosTipopagoses, Set civDetalleRecUsus, Set civValorinfraccions, Set civAttemptses) {
       this.usuId = usuId;
       this.civPersonas = civPersonas;
       this.usuNombre = usuNombre;
       this.usuPassword = usuPassword;
       this.usuEstado = usuEstado;
       this.usuFechainicial = usuFechainicial;
       this.usuFechafinal = usuFechafinal;
       this.usuFechaproceso = usuFechaproceso;
       this.civUsuarioCajases = civUsuarioCajases;
       this.logEventoses = logEventoses;
       this.civUspHistorias = civUspHistorias;
       this.civPerfilrecursos = civPerfilrecursos;
       this.civUsuariosTipopagoses = civUsuariosTipopagoses;
       this.civDetalleRecUsus = civDetalleRecUsus;
       this.civValorinfraccions = civValorinfraccions;
       this.civAttemptses = civAttemptses;
    }
   
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }
    public CivPersonas getCivPersonas() {
        return this.civPersonas;
    }
    
    public void setCivPersonas(CivPersonas civPersonas) {
        this.civPersonas = civPersonas;
    }
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }
    public String getUsuPassword() {
        return this.usuPassword;
    }
    
    public void setUsuPassword(String usuPassword) {
        this.usuPassword = usuPassword;
    }
    public BigDecimal getUsuEstado() {
        return this.usuEstado;
    }
    
    public void setUsuEstado(BigDecimal usuEstado) {
        this.usuEstado = usuEstado;
    }
    public Date getUsuFechainicial() {
        return this.usuFechainicial;
    }
    
    public void setUsuFechainicial(Date usuFechainicial) {
        this.usuFechainicial = usuFechainicial;
    }
    public Date getUsuFechafinal() {
        return this.usuFechafinal;
    }
    
    public void setUsuFechafinal(Date usuFechafinal) {
        this.usuFechafinal = usuFechafinal;
    }
    public Date getUsuFechaproceso() {
        return this.usuFechaproceso;
    }
    
    public void setUsuFechaproceso(Date usuFechaproceso) {
        this.usuFechaproceso = usuFechaproceso;
    }
    public Set getCivUsuarioCajases() {
        return this.civUsuarioCajases;
    }
    
    public void setCivUsuarioCajases(Set civUsuarioCajases) {
        this.civUsuarioCajases = civUsuarioCajases;
    }
    public Set getLogEventoses() {
        return this.logEventoses;
    }
    
    public void setLogEventoses(Set logEventoses) {
        this.logEventoses = logEventoses;
    }
    public Set getCivUspHistorias() {
        return this.civUspHistorias;
    }
    
    public void setCivUspHistorias(Set civUspHistorias) {
        this.civUspHistorias = civUspHistorias;
    }
    public Set getCivPerfilrecursos() {
        return this.civPerfilrecursos;
    }
    
    public void setCivPerfilrecursos(Set civPerfilrecursos) {
        this.civPerfilrecursos = civPerfilrecursos;
    }
    public Set getCivUsuariosTipopagoses() {
        return this.civUsuariosTipopagoses;
    }
    
    public void setCivUsuariosTipopagoses(Set civUsuariosTipopagoses) {
        this.civUsuariosTipopagoses = civUsuariosTipopagoses;
    }
    public Set getCivDetalleRecUsus() {
        return this.civDetalleRecUsus;
    }
    
    public void setCivDetalleRecUsus(Set civDetalleRecUsus) {
        this.civDetalleRecUsus = civDetalleRecUsus;
    }
    public Set getCivValorinfraccions() {
        return this.civValorinfraccions;
    }
    
    public void setCivValorinfraccions(Set civValorinfraccions) {
        this.civValorinfraccions = civValorinfraccions;
    }
    public Set getCivAttemptses() {
        return this.civAttemptses;
    }
    
    public void setCivAttemptses(Set civAttemptses) {
        this.civAttemptses = civAttemptses;
    }




}


