package com.contravenciones.tr.persistence;
// Generated 1/02/2018 01:51:55 PM by Hibernate Tools 4.3.1



/**
 * CivUsuarioCajas generated by hbm2java
 */
public class CivUsuarioCajas  implements java.io.Serializable {


     private CivUsuarioCajasId id;
     private CivUsuarios civUsuarios;
     private CivCajas civCajas;

    public CivUsuarioCajas() {
    }

    public CivUsuarioCajas(CivUsuarioCajasId id, CivUsuarios civUsuarios, CivCajas civCajas) {
       this.id = id;
       this.civUsuarios = civUsuarios;
       this.civCajas = civCajas;
    }
   
    public CivUsuarioCajasId getId() {
        return this.id;
    }
    
    public void setId(CivUsuarioCajasId id) {
        this.id = id;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public CivCajas getCivCajas() {
        return this.civCajas;
    }
    
    public void setCivCajas(CivCajas civCajas) {
        this.civCajas = civCajas;
    }




}


