package com.contravenciones.tr.persistence;
// Generated 1/02/2018 01:51:55 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivUsuarioCajasId generated by hbm2java
 */
public class CivUsuarioCajasId  implements java.io.Serializable {


     private long usuId;
     private BigDecimal cajId;
     private Date usucajFechaInicio;
     private Date usucajFechaFin;

    public CivUsuarioCajasId() {
    }

	
    public CivUsuarioCajasId(long usuId, BigDecimal cajId, Date usucajFechaInicio) {
        this.usuId = usuId;
        this.cajId = cajId;
        this.usucajFechaInicio = usucajFechaInicio;
    }
    public CivUsuarioCajasId(long usuId, BigDecimal cajId, Date usucajFechaInicio, Date usucajFechaFin) {
       this.usuId = usuId;
       this.cajId = cajId;
       this.usucajFechaInicio = usucajFechaInicio;
       this.usucajFechaFin = usucajFechaFin;
    }
   
    public long getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(long usuId) {
        this.usuId = usuId;
    }
    public BigDecimal getCajId() {
        return this.cajId;
    }
    
    public void setCajId(BigDecimal cajId) {
        this.cajId = cajId;
    }
    public Date getUsucajFechaInicio() {
        return this.usucajFechaInicio;
    }
    
    public void setUsucajFechaInicio(Date usucajFechaInicio) {
        this.usucajFechaInicio = usucajFechaInicio;
    }
    public Date getUsucajFechaFin() {
        return this.usucajFechaFin;
    }
    
    public void setUsucajFechaFin(Date usucajFechaFin) {
        this.usucajFechaFin = usucajFechaFin;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CivUsuarioCajasId) ) return false;
		 CivUsuarioCajasId castOther = ( CivUsuarioCajasId ) other; 
         
		 return (this.getUsuId()==castOther.getUsuId())
 && ( (this.getCajId()==castOther.getCajId()) || ( this.getCajId()!=null && castOther.getCajId()!=null && this.getCajId().equals(castOther.getCajId()) ) )
 && ( (this.getUsucajFechaInicio()==castOther.getUsucajFechaInicio()) || ( this.getUsucajFechaInicio()!=null && castOther.getUsucajFechaInicio()!=null && this.getUsucajFechaInicio().equals(castOther.getUsucajFechaInicio()) ) )
 && ( (this.getUsucajFechaFin()==castOther.getUsucajFechaFin()) || ( this.getUsucajFechaFin()!=null && castOther.getUsucajFechaFin()!=null && this.getUsucajFechaFin().equals(castOther.getUsucajFechaFin()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getUsuId();
         result = 37 * result + ( getCajId() == null ? 0 : this.getCajId().hashCode() );
         result = 37 * result + ( getUsucajFechaInicio() == null ? 0 : this.getUsucajFechaInicio().hashCode() );
         result = 37 * result + ( getUsucajFechaFin() == null ? 0 : this.getUsucajFechaFin().hashCode() );
         return result;
   }   


}


