package com.contravenciones.tr.persistence;
// Generated 5/02/2018 01:39:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivUsuariosTipopagos generated by hbm2java
 */
public class CivUsuariosTipopagos  implements java.io.Serializable {


     private CivUsuariosTipopagosId id;
     private CivUsuarios civUsuarios;
     private CivTipopagos civTipopagos;
     private BigDecimal ustipEstado;
     private Date fechafin;
     private Date fechainicial;

    public CivUsuariosTipopagos() {
    }

	
    public CivUsuariosTipopagos(CivUsuariosTipopagosId id, CivUsuarios civUsuarios, CivTipopagos civTipopagos, BigDecimal ustipEstado, Date fechainicial) {
        this.id = id;
        this.civUsuarios = civUsuarios;
        this.civTipopagos = civTipopagos;
        this.ustipEstado = ustipEstado;
        this.fechainicial = fechainicial;
    }
    public CivUsuariosTipopagos(CivUsuariosTipopagosId id, CivUsuarios civUsuarios, CivTipopagos civTipopagos, BigDecimal ustipEstado, Date fechafin, Date fechainicial) {
       this.id = id;
       this.civUsuarios = civUsuarios;
       this.civTipopagos = civTipopagos;
       this.ustipEstado = ustipEstado;
       this.fechafin = fechafin;
       this.fechainicial = fechainicial;
    }
   
    public CivUsuariosTipopagosId getId() {
        return this.id;
    }
    
    public void setId(CivUsuariosTipopagosId id) {
        this.id = id;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public CivTipopagos getCivTipopagos() {
        return this.civTipopagos;
    }
    
    public void setCivTipopagos(CivTipopagos civTipopagos) {
        this.civTipopagos = civTipopagos;
    }
    public BigDecimal getUstipEstado() {
        return this.ustipEstado;
    }
    
    public void setUstipEstado(BigDecimal ustipEstado) {
        this.ustipEstado = ustipEstado;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public Date getFechainicial() {
        return this.fechainicial;
    }
    
    public void setFechainicial(Date fechainicial) {
        this.fechainicial = fechainicial;
    }




}


