package com.contravenciones.tr.persistence;
// Generated 22/01/2018 03:31:24 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivUsuarios generated by hbm2java
 */
public class CivUsuarios  implements java.io.Serializable {


     private BigDecimal usuId;
     private CivSedes civSedes;
     private CivPersonas civPersonas;
     private String usuNombre;
     private String usuPassword;
     private BigDecimal usuEstado;
     private Date usuFechainicial;
     private Date usuFechafinal;
     private Date usuFechaproceso;
     private BigDecimal usuUsuariorunt;
     private Set civSalariosminimoses = new HashSet(0);
     private Set civUspHistorias = new HashSet(0);
     private Set civValorinfraccions = new HashSet(0);
     private Set civCarterases = new HashSet(0);
     private Set civPerfilrecursos = new HashSet(0);
     private Set civInfraccioneses = new HashSet(0);
     private Set civConceptoses = new HashSet(0);
     private Set civUsuarioCajases = new HashSet(0);
     private Set civDetallecarteras = new HashSet(0);
     private Set civAttemptses = new HashSet(0);
     private Set civDatosParametricoses = new HashSet(0);
     private Set civDetalleRecUsus = new HashSet(0);
     private Set civUsuperfils = new HashSet(0);

    public CivUsuarios() {
    }

	
    public CivUsuarios(BigDecimal usuId, CivSedes civSedes, CivPersonas civPersonas, String usuNombre, String usuPassword, BigDecimal usuEstado, Date usuFechainicial, Date usuFechaproceso, BigDecimal usuUsuariorunt) {
        this.usuId = usuId;
        this.civSedes = civSedes;
        this.civPersonas = civPersonas;
        this.usuNombre = usuNombre;
        this.usuPassword = usuPassword;
        this.usuEstado = usuEstado;
        this.usuFechainicial = usuFechainicial;
        this.usuFechaproceso = usuFechaproceso;
        this.usuUsuariorunt = usuUsuariorunt;
    }
    public CivUsuarios(BigDecimal usuId, CivSedes civSedes, CivPersonas civPersonas, String usuNombre, String usuPassword, BigDecimal usuEstado, Date usuFechainicial, Date usuFechafinal, Date usuFechaproceso, BigDecimal usuUsuariorunt, Set civSalariosminimoses, Set civUspHistorias, Set civValorinfraccions, Set civCarterases, Set civPerfilrecursos, Set civInfraccioneses, Set civConceptoses, Set civUsuarioCajases, Set civDetallecarteras, Set civAttemptses, Set civDatosParametricoses, Set civDetalleRecUsus, Set civUsuperfils) {
       this.usuId = usuId;
       this.civSedes = civSedes;
       this.civPersonas = civPersonas;
       this.usuNombre = usuNombre;
       this.usuPassword = usuPassword;
       this.usuEstado = usuEstado;
       this.usuFechainicial = usuFechainicial;
       this.usuFechafinal = usuFechafinal;
       this.usuFechaproceso = usuFechaproceso;
       this.usuUsuariorunt = usuUsuariorunt;
       this.civSalariosminimoses = civSalariosminimoses;
       this.civUspHistorias = civUspHistorias;
       this.civValorinfraccions = civValorinfraccions;
       this.civCarterases = civCarterases;
       this.civPerfilrecursos = civPerfilrecursos;
       this.civInfraccioneses = civInfraccioneses;
       this.civConceptoses = civConceptoses;
       this.civUsuarioCajases = civUsuarioCajases;
       this.civDetallecarteras = civDetallecarteras;
       this.civAttemptses = civAttemptses;
       this.civDatosParametricoses = civDatosParametricoses;
       this.civDetalleRecUsus = civDetalleRecUsus;
       this.civUsuperfils = civUsuperfils;
    }
   
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }
    public CivSedes getCivSedes() {
        return this.civSedes;
    }
    
    public void setCivSedes(CivSedes civSedes) {
        this.civSedes = civSedes;
    }
    public CivPersonas getCivPersonas() {
        return this.civPersonas;
    }
    
    public void setCivPersonas(CivPersonas civPersonas) {
        this.civPersonas = civPersonas;
    }
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }
    public String getUsuPassword() {
        return this.usuPassword;
    }
    
    public void setUsuPassword(String usuPassword) {
        this.usuPassword = usuPassword;
    }
    public BigDecimal getUsuEstado() {
        return this.usuEstado;
    }
    
    public void setUsuEstado(BigDecimal usuEstado) {
        this.usuEstado = usuEstado;
    }
    public Date getUsuFechainicial() {
        return this.usuFechainicial;
    }
    
    public void setUsuFechainicial(Date usuFechainicial) {
        this.usuFechainicial = usuFechainicial;
    }
    public Date getUsuFechafinal() {
        return this.usuFechafinal;
    }
    
    public void setUsuFechafinal(Date usuFechafinal) {
        this.usuFechafinal = usuFechafinal;
    }
    public Date getUsuFechaproceso() {
        return this.usuFechaproceso;
    }
    
    public void setUsuFechaproceso(Date usuFechaproceso) {
        this.usuFechaproceso = usuFechaproceso;
    }
    public BigDecimal getUsuUsuariorunt() {
        return this.usuUsuariorunt;
    }
    
    public void setUsuUsuariorunt(BigDecimal usuUsuariorunt) {
        this.usuUsuariorunt = usuUsuariorunt;
    }
    public Set getCivSalariosminimoses() {
        return this.civSalariosminimoses;
    }
    
    public void setCivSalariosminimoses(Set civSalariosminimoses) {
        this.civSalariosminimoses = civSalariosminimoses;
    }
    public Set getCivUspHistorias() {
        return this.civUspHistorias;
    }
    
    public void setCivUspHistorias(Set civUspHistorias) {
        this.civUspHistorias = civUspHistorias;
    }
    public Set getCivValorinfraccions() {
        return this.civValorinfraccions;
    }
    
    public void setCivValorinfraccions(Set civValorinfraccions) {
        this.civValorinfraccions = civValorinfraccions;
    }
    public Set getCivCarterases() {
        return this.civCarterases;
    }
    
    public void setCivCarterases(Set civCarterases) {
        this.civCarterases = civCarterases;
    }
    public Set getCivPerfilrecursos() {
        return this.civPerfilrecursos;
    }
    
    public void setCivPerfilrecursos(Set civPerfilrecursos) {
        this.civPerfilrecursos = civPerfilrecursos;
    }
    public Set getCivInfraccioneses() {
        return this.civInfraccioneses;
    }
    
    public void setCivInfraccioneses(Set civInfraccioneses) {
        this.civInfraccioneses = civInfraccioneses;
    }
    public Set getCivConceptoses() {
        return this.civConceptoses;
    }
    
    public void setCivConceptoses(Set civConceptoses) {
        this.civConceptoses = civConceptoses;
    }
    public Set getCivUsuarioCajases() {
        return this.civUsuarioCajases;
    }
    
    public void setCivUsuarioCajases(Set civUsuarioCajases) {
        this.civUsuarioCajases = civUsuarioCajases;
    }
    public Set getCivDetallecarteras() {
        return this.civDetallecarteras;
    }
    
    public void setCivDetallecarteras(Set civDetallecarteras) {
        this.civDetallecarteras = civDetallecarteras;
    }
    public Set getCivAttemptses() {
        return this.civAttemptses;
    }
    
    public void setCivAttemptses(Set civAttemptses) {
        this.civAttemptses = civAttemptses;
    }
    public Set getCivDatosParametricoses() {
        return this.civDatosParametricoses;
    }
    
    public void setCivDatosParametricoses(Set civDatosParametricoses) {
        this.civDatosParametricoses = civDatosParametricoses;
    }
    public Set getCivDetalleRecUsus() {
        return this.civDetalleRecUsus;
    }
    
    public void setCivDetalleRecUsus(Set civDetalleRecUsus) {
        this.civDetalleRecUsus = civDetalleRecUsus;
    }
    public Set getCivUsuperfils() {
        return this.civUsuperfils;
    }
    
    public void setCivUsuperfils(Set civUsuperfils) {
        this.civUsuperfils = civUsuperfils;
    }




}


