package com.contravenciones.tr.persistence;
// Generated 15/01/2018 03:21:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CivUsuarioCajas generated by hbm2java
 */
public class CivUsuarioCajas  implements java.io.Serializable {


     private CivUsuarioCajasId id;
     private CivCajas civCajas;
     private CivSedes civSedes;
     private CivUsuarios civUsuarios;
     private Date usucajFechaInicio;
     private Date usucajFechaFin;

    public CivUsuarioCajas() {
    }

	
    public CivUsuarioCajas(CivUsuarioCajasId id, CivCajas civCajas, CivSedes civSedes, CivUsuarios civUsuarios, Date usucajFechaInicio) {
        this.id = id;
        this.civCajas = civCajas;
        this.civSedes = civSedes;
        this.civUsuarios = civUsuarios;
        this.usucajFechaInicio = usucajFechaInicio;
    }
    public CivUsuarioCajas(CivUsuarioCajasId id, CivCajas civCajas, CivSedes civSedes, CivUsuarios civUsuarios, Date usucajFechaInicio, Date usucajFechaFin) {
       this.id = id;
       this.civCajas = civCajas;
       this.civSedes = civSedes;
       this.civUsuarios = civUsuarios;
       this.usucajFechaInicio = usucajFechaInicio;
       this.usucajFechaFin = usucajFechaFin;
    }
   
    public CivUsuarioCajasId getId() {
        return this.id;
    }
    
    public void setId(CivUsuarioCajasId id) {
        this.id = id;
    }
    public CivCajas getCivCajas() {
        return this.civCajas;
    }
    
    public void setCivCajas(CivCajas civCajas) {
        this.civCajas = civCajas;
    }
    public CivSedes getCivSedes() {
        return this.civSedes;
    }
    
    public void setCivSedes(CivSedes civSedes) {
        this.civSedes = civSedes;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public Date getUsucajFechaInicio() {
        return this.usucajFechaInicio;
    }
    
    public void setUsucajFechaInicio(Date usucajFechaInicio) {
        this.usucajFechaInicio = usucajFechaInicio;
    }
    public Date getUsucajFechaFin() {
        return this.usucajFechaFin;
    }
    
    public void setUsucajFechaFin(Date usucajFechaFin) {
        this.usucajFechaFin = usucajFechaFin;
    }




}


