package com.contravenciones.tr.persistence;
// Generated 5/02/2018 01:39:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CivUsuariosTipopagosId generated by hbm2java
 */
public class CivUsuariosTipopagosId  implements java.io.Serializable {


     private long usuId;
     private BigDecimal tippagId;

    public CivUsuariosTipopagosId() {
    }

    public CivUsuariosTipopagosId(long usuId, BigDecimal tippagId) {
       this.usuId = usuId;
       this.tippagId = tippagId;
    }
   
    public long getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(long usuId) {
        this.usuId = usuId;
    }
    public BigDecimal getTippagId() {
        return this.tippagId;
    }
    
    public void setTippagId(BigDecimal tippagId) {
        this.tippagId = tippagId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CivUsuariosTipopagosId) ) return false;
		 CivUsuariosTipopagosId castOther = ( CivUsuariosTipopagosId ) other; 
         
		 return (this.getUsuId()==castOther.getUsuId())
 && ( (this.getTippagId()==castOther.getTippagId()) || ( this.getTippagId()!=null && castOther.getTippagId()!=null && this.getTippagId().equals(castOther.getTippagId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getUsuId();
         result = 37 * result + ( getTippagId() == null ? 0 : this.getTippagId().hashCode() );
         return result;
   }   


}


